In [1]:
import pandas as pd

directory = r'data\\'

In [2]:
df = pd.read_excel(directory + 'Pulp Fiction.xlsx')
df.head()

,Start Time,End Time,Character,Subtitle,Fuck Count,Fuck Count 2,Check,Part,start_seconds,end_seconds
0,"00:00:28,340","00:00:32,428",Pumpkin,Forget it. It's too risky. I'm through doing t...,0,0,0,Prologue – The Diner,28.340,32.428
1,"00:00:32,508","00:00:35,966",Honey Bunny,You always say that. The same thing every time.,0,0,0,Prologue – The Diner,32.508,35.966
2,"00:00:36,038","00:00:37,977",Honey Bunny,"""I'm through, never again, too dangerous.""",0,0,0,Prologue – The Diner,36.038,37.977
3,"00:00:38,048","00:00:40,537",Pumpkin,I know that's what I always say. I'm always ri...,0,0,0,Prologue – The Diner,38.048,40.537
4,"00:00:40,617","00:00:44,015",Pumpkin,The days of me forgetting are over.,0,0,0,Prologue – The Diner,40.617,44.015

In [3]:
def count_occurrences(word, sentence):
    # Count occurrences of the word in the sentence, case insensitive
    return sentence.lower().count(word.lower())

# Adding a new column 'Fuck Count' to the DataFrame
df['Fuck Count 3'] = df['Subtitle'].apply(lambda x: count_occurrences('fuck', x))

# Displaying the DataFrame with the new column
df.head()

,Start Time,End Time,Character,Subtitle,Fuck Count,Fuck Count 2,Check,Part,start_seconds,end_seconds,Fuck Count 3
0,"00:00:28,340","00:00:32,428",Pumpkin,Forget it. It's too risky. I'm through doing t...,0,0,0,Prologue – The Diner,28.340,32.428,0
1,"00:00:32,508","00:00:35,966",Honey Bunny,You always say that. The same thing every time.,0,0,0,Prologue – The Diner,32.508,35.966,0
2,"00:00:36,038","00:00:37,977",Honey Bunny,"""I'm through, never again, too dangerous.""",0,0,0,Prologue – The Diner,36.038,37.977,0
3,"00:00:38,048","00:00:40,537",Pumpkin,I know that's what I always say. I'm always ri...,0,0,0,Prologue – The Diner,38.048,40.537,0
4,"00:00:40,617","00:00:44,015",Pumpkin,The days of me forgetting are over.,0,0,0,Prologue – The Diner,40.617,44.015,0

In [4]:
df[df['Fuck Count'] != df['Fuck Count 3']]

Empty DataFrame
Columns: [Start Time, End Time, Character, Subtitle, Fuck Count, Fuck Count 2, Check, Part, start_seconds, end_seconds, Fuck Count 3]
Index: []

In [5]:
df['Fuck Count'].sum()

271

In [6]:
df.drop(['Fuck Count 2', 'Fuck Count 3'], axis=1, inplace=True)

In [7]:
subtitles = pd.read_excel(directory + 'subtitles.xlsx')
subtitles.head()

,Start Time,End Time,Subtitle,Fuck Count,Fuck Count 2,start_seconds,end_seconds
0,"00:00:28,340","00:00:32,428",Forget it. It's too risky. I'm through doing t...,0,0,28.340,32.428
1,"00:00:32,508","00:00:35,966",You always say that. The same thing every time.,0,0,32.508,35.966
2,"00:00:36,038","00:00:37,977","""I'm through, never again, too dangerous.""",0,0,36.038,37.977
3,"00:00:38,048","00:00:40,537",I know that's what I always say. I'm always ri...,0,0,38.048,40.537
4,"00:00:40,617","00:00:44,015",The days of me forgetting are over.,0,0,40.617,44.015

In [8]:
subtitles = subtitles[['start_seconds', 'Subtitle', 'Fuck Count']].set_index('start_seconds')

df = df.join(subtitles, on='start_seconds', how='left', rsuffix=' 2')

In [12]:
df[df['Fuck Count'] != df['Fuck Count 2']].to_excel(directory + 'fuck_check.xlsx', index=False)